title: Fuzzywalls Blog
description: Ramblings about code on my Github or random things I found interesting.
show_downloads: false
google_analytics: UA-163283130-1
theme: jekyll-theme-midnight
permalink: "/:categories/:title.html"